### ISSUE TITLE
Travis CI failing

### ISSUE THREAD

**Issue by evgeniy-pupkov** [nkinder/ansible-keycloak#22]
Hello!
I can see that Travis CI builds necessary for Ansible Galaxy fails on 'configure firewall for Keycloak ports' task. It seems that this task tries to open ports before firewalld service completes startup. I propose to add a looped check task before it. Something like this should work:
```yml
- name: check if firewalld started
  shell:
    cmd: firewall-cmd --state 
  register: firewalld_state
  until: >
    'running' in firewalld_state.stdout
  retries: 60
  delay: 5
```
I'm going to create a PR, and if it fails on Travis CI, I'll try to fix it
